version: 2.1

orbs:
  coveralls: coveralls/coveralls@x.y.z

jobs:
  build:
    docker:
      - image: circleci/node:10.0.0

    steps:
      - run: 
          name: Install and Make
          command: npm install && make test-coverage
      - coveralls/upload

  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: python3 -m unittest -v

workflows:
  build_and_test:
    jobs:
      - test
      - build